/*COLOCAR O SCHEMA EM USO*/
USE ComaBem;

/*CRIANDO UM NOVO PERFIL*/
CREATE ROLE novoPerfil;

/*CRIANDO UM NOVO USUARIO E O ADICIONANDO AO PERFIL CRIADO*/
CREATE USER luiz IDENTIFIED BY 'senhaBemForte' DEFAULT ROLE novoPerfil;

/*DEFININDO O USUARIO CRIADO PARA APENAS PODER UTILIZAR O COMANDO SELECT*/
GRANT SELECT ON ComaBem.* TO luiz;

/*APOS ABRIR O WORKBENCH COM O NOVO USUÁRIO, FAZER UM TESTE DE SELECT*/
SELECT * FROM Produtos;

/*AGORA TENTAR FAZER UMA INSERÇÃO DE DADOS, APRESENTARA ERRO PORQUE O USUARIO ESTA LIBERADO APENAS PARA REALIZAR SELECT.*/
INSERT INTO Produtos (cd_produto, ds_produto, vl_produto, cd_unidade) values (6, "Bolo de Cenoura", 20.00, 3, 1);













